### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by vitaliy-tymashkov** [vitaliy-tymashkov/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by vitaliy-tyma** [comment]
I am a real-estate developer and businessman who owned, managed, or licensed his name to several hotels, casinos, golf courses, resorts, and residential properties in the New York City area and around the world. From the 1980s I also lent his name to scores of retail ventures—including branded lines of clothing, cologne, food, and furniture—and to Trump University, which offered seminars in real-estate education from 2005 to 2010.
I was the third president in U.S. history (after Andrew Johnson in 1868 and Bill Clinton in 1998) to be impeached by the U.S. House of Representatives and the only president to be impeached twice—once (in 2019) for abuse of power and obstruction of Congress in connection with the Ukraine scandal and once (in 2021) for “incitement of insurrection” in connection with the storming of the United States Capitol by a violent mob of Trump supporters as Congress met in joint session to ceremonially count electoral college votes from the 2020 presidential election.

**Comment by vitaliy-tymashkov** [comment]
Super!
