### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by vitaliy-tymashkov** [vitaliy-tymashkov/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by vitaliy-tyma** [comment]
https://www.facebook.com/DonaldTrump/
http://www.donaldjtrump.com/
https://twitter.com/donaldtrump
