### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by vitaliy-tymashkov** [vitaliy-tymashkov/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by vitaliy-tyma** [comment]
Below is an abbreviated outline of Trump's professional and political career:[12][13][14]

2017-2021: President of the United States
1971-2017: President, The Trump Organization
2004-2015: Producer and host, The Apprentice
1996-2015: Owner, Miss Universe Organization
1987: Author, The Art of the Deal
1968: Graduated with B.S. in economics from the Wharton School of Finance at the University of Pennsylvania
